[general]
shuffle_caption = false
caption_extension = '.txt'

[[datasets]]
resolution = [512, 512]
batch_size = 1
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 768
bucket_reso_steps = 16
bucket_no_upscale = true

  [[datasets.subsets]]
  image_dir = 'D:\SDXL\ai-toolkit\datasets\1_wang yu wen'
  num_repeats = 1
  caption_extension = '.txt'

[[datasets]]
resolution = [640, 640]
batch_size = 1
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1024
bucket_reso_steps = 16
bucket_no_upscale = true

  [[datasets.subsets]]
  image_dir = 'D:\SDXL\ai-toolkit\datasets\1_wang yu wen'
  num_repeats = 1
  caption_extension = '.txt'

[[datasets]]
resolution = [768, 768]
batch_size = 1
enable_bucket = true
min_bucket_reso = 384
max_bucket_reso = 1152
bucket_reso_steps = 16
bucket_no_upscale = true

  [[datasets.subsets]]
  image_dir = 'D:\SDXL\ai-toolkit\datasets\1_wang yu wen'
  num_repeats = 1
  caption_extension = '.txt'

[[datasets]]
resolution = [1024, 1024]
batch_size = 1
enable_bucket = true
min_bucket_reso = 512
max_bucket_reso = 1280
bucket_reso_steps = 16
bucket_no_upscale = true

  [[datasets.subsets]]
  image_dir = 'D:\SDXL\ai-toolkit\datasets\1_wang yu wen'
  num_repeats = 1
  caption_extension = '.txt'
