[general]
shuffle_caption = false
caption_extension = '.txt'

[[datasets]]
resolution = [1024, 1024]
batch_size = 1
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1536
bucket_reso_steps = 32
bucket_no_upscale = false

  [[datasets.subsets]]
  # Change this to your training image folder.
  image_dir = 'D:/SDXL/ai-toolkit/datasets/1_loli'
  num_repeats = 1
  caption_extension = '.txt'
  class_tokens = 'loli'
